[Icon Theme]
Name=Paper
Comment=A simple and modern icon theme.
Inherits=elementary
Example=folder


# Directory list
Directories=16x16/panel,24x24/panel,scalable/status

# Panel

[16x16/panel]
Context=Status
Size=16
Type=Fixed

[22x22/panel]
Context=Status
Size=22
Type=Fixed

[24x24/panel]
Context=Status
Size=24
Type=Fixed

[scalable/status]
Context=Status
Size=16
MinSize=16
MaxSize=16
Type=Fixed

